import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#f0eded",
        error: "#ba1a1a",
        "surface-variant": "#e5e2e1",
        "on-surface-variant": "#404943",
        "surface-container-highest": "#e5e2e1",
        "surface-tint": "#2c694e",
        "on-secondary": "#ffffff",
        secondary: "#5d5f5f",
        "inverse-primary": "#95d4b3",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-container-high": "#eae7e7",
        "surface-bright": "#fcf9f8",
        "on-secondary-container": "#5f6161",
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "on-background": "#1c1b1b",
        "secondary-fixed-dim": "#c6c6c7",
        "secondary-fixed": "#e2e2e2",
        "on-primary-fixed": "#002114",
        "tertiary-container": "#a73b19",
        "primary-fixed-dim": "#95d4b3",
        "primary-fixed": "#b1f0ce",
        tertiary: "#862402",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb5a0",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f3f0ef",
        "on-primary-container": "#a8e7c5",
        "on-tertiary-container": "#ffcfc2",
        "tertiary-fixed": "#ffdbd1",
        "on-tertiary-fixed-variant": "#862302",
        "on-tertiary-fixed": "#3b0a00",
        "on-primary": "#ffffff",
        "secondary-container": "#dcdddd",
        "on-secondary-fixed": "#1a1c1c",
        "outline-variant": "#bfc9c1",
        background: "#fcf9f8",
        "primary-container": "#2d6a4f",
        "on-surface": "#1c1b1b",
        "on-secondary-fixed-variant": "#454747",
        primary: "#0f5238",
        outline: "#707973",
        "on-primary-fixed-variant": "#0e5138",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-tertiary": "#ffffff",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "system-ui", "sans-serif"],
        body: ["var(--font-inter)", "system-ui", "sans-serif"],
        label: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
